[workspace]
members = [
    "crates/devices/*",
    "crates/virtio-bindings",
    "crates/virtio-device",
    "crates/virtio-queue",
    "crates/virtio-queue-ser",
]

[profile.bench]
lto = true
codegen-units = 1
